#!/bin/bash

## source this from your login shell

prod_domain="prod.c2gops.com"
stage_domain="stage2.c2gops.com"
dev_domain="dev.c2gops.com"

ssh_options="-A"

alias app.prod="ssh ${ssh_options} bitnami@app1.${prod_domain}"
alias util.prod="ssh ${ssh_options} ubuntu@util1.${prod_domain}"

alias app.stage="ssh ${ssh_options} bitnami@app1.${stage_domain}"
alias app1.stage="ssh ${ssh_options} bitnami@app1.${stage_domain}"
alias app2.stage="ssh ${ssh_options} bitnami@app2.${stage_domain}"
alias util.stage="ssh ${ssh_options} ubuntu@util1.${stage_domain}"
alias util1.stage="ssh ${ssh_options} ubuntu@util1.${stage_domain}"

alias jenkins="ssh ${ssh_options} ubuntu@jenkins.${dev_domain}"
alias deploy="ssh ${ssh_options} deploy.${dev_domain}"  # as user

alias localdb="~/src/class2go/main/manage.py dbshell"

function multitail-prod {
    multitail -s 2  \
        --config /usr/local/etc/multitail.conf \
        -CS apache \
        -l 'ssh bitnami@app1.prod.c2gops.com "tail -f stack/apache2/logs/access_log"' \
        -l 'ssh bitnami@app2.prod.c2gops.com "tail -f stack/apache2/logs/access_log"' \
        -l 'ssh bitnami@app3.prod.c2gops.com "tail -f stack/apache2/logs/access_log"' \
        -c- \
        -l 'ssh ubuntu@util1.prod.c2gops.com "tail -f /var/log/celery/*.log"' \
        -CS apache_error \
        -l 'ssh bitnami@app1.prod.c2gops.com "tail -f stack/apache2/logs/error_log"' \
        -l 'ssh bitnami@app2.prod.c2gops.com "tail -f stack/apache2/logs/error_log"' \
        -l 'ssh bitnami@app3.prod.c2gops.com "tail -f stack/apache2/logs/error_log"' \
        -c- \
        -l 'ssh ubuntu@util1.prod.c2gops.com "tail -f /var/log/django/kelvinator.log"' 
}



function multitail-prod-util {
    multitail -s 2  \
        --config /usr/local/etc/multitail.conf \
        -l 'ssh ubuntu@util1.prod.c2gops.com "tail -f /var/log/celery/*.log"' \
        -l 'ssh ubuntu@util2.prod.c2gops.com "tail -f /var/log/celery/*.log"' 
}



function multitail-stage {
    multitail -s 2  \
        --config /usr/local/etc/multitail.conf \
        -CS apache \
        -l 'ssh bitnami@app1.stage.c2gops.com "tail -f stack/apache2/logs/access_log"' \
        -l 'ssh bitnami@app2.stage.c2gops.com "tail -f stack/apache2/logs/access_log"' \
        -c- \
        -l 'ssh ubuntu@util1.stage.c2gops.com "tail -f /var/log/celery/*.log"' \
        -CS apache_error \
        -l 'ssh bitnami@app1.stage.c2gops.com "tail -f stack/apache2/logs/error_log"' \
        -l 'ssh bitnami@app2.stage.c2gops.com "tail -f stack/apache2/logs/error_log"' \
        -c- \
        -l 'ssh ubuntu@util1.stage.c2gops.com "tail -f /var/log/django/kelvinator.log"' 
}
