#!/bin/bash
#
# Scripts for bug lists of different sorts 
#
# All rely on ghi, the nice set of comand line tools on top of the Github 
# issues API. https://github.com/stephencelis/ghi
#
# Note that currently this relies on printing milestone and assignments in
# bug list, a change made in my own fork: https://github.com/sefk/ghi
#

function buglist-by-dev {
    if [[ $# -eq 1 ]]; then
        sprintparam="-M $1"
    fi

    for a in dcadams halawa jbau jinpa sefk wescott shalinguyen kelvindo kluo ; do
        for p in P0 P1; do
            echo "**** $a ($p) ****"
            ghi list -q -s open -l $p -u $a -q $sprintparam | grep -v '\[3-Done\]'
        done
        echo; echo
    done

    for p in P0 P1; do
        echo "**** nobody ($p) ****"
        ghi list -q -l $p -s open ${sinceparam} -q $sprintparam | grep -v '\[3-Done\]' | grep -E "^#|NO-ASGN"
    done
}

function buglist-counts {
    NOW=`date -u +"%F %R UTC"`
    case `uname` in
        "Darwin" )
            YESTERDAY=`date -v -1d` ;;
        * )
            YESTERDAY=`date --date="yesterday"` ;;
    esac

    for l in P0 P1 P2; do
        # echo -ne "${NOW}\t"
        echo -ne "$l\t"
        ghi list -q -s open -l $l | grep -v '3-Done' | wc -l | tr -d ' ' | tr -d '\n'

        ACTIVE=`ghi list -q -s open -l $l --since "${YESTERDAY}" | grep -v '3-Done' | wc -l | tr -d ' '`
        echo -ne "\t (${ACTIVE} active)"
        echo
    done
}

function buglist-active {
    case `uname` in
        "Darwin" )
            YESTERDAY=`date -v -1d` ;;
        * )
            YESTERDAY=`date --date="yesterday"` ;;
    esac
    echo -ne '# Marked as Not Done, '
    ghi list -s open --since "${YESTERDAY}"  | grep -v '3-Done'
    echo -ne '# Marked as Done, '
    ghi list -s open --since "${YESTERDAY}"  | egrep '^#|3-Done'
    ghi list -s closed --since "${YESTERDAY}"
}

function buglist-hot {
    ghi list -s open -l P0 | grep -v '3-Done' 
}

function buglist-to-triage {
    if [[ $1 == "new" ]]; then
        case `uname` in
            "Darwin" )
                YESTERDAY=`date -v -1d` ;;
            * )
                YESTERDAY=`date --date="yesterday"` ;;
        esac
        sinceparam="--since ${YESTERDAY}"
        sincemsg=" (PRIOR 24 HOURS)"
    else
        sinceparam=""
        sincemsg=""
    fi

    echo "MISSING PRIORITY${sincemsg}"
    ghi list -s open ${sinceparam} \
        | grep -v "NO-ASGN" \
        | grep -v "\[P0\]" \
        | grep -v "\[P1\]" \
        | grep -v "\[P2\]" \
        | grep -v "\[P3\]" 
    echo
    echo "NOT ASSIGNED${sincemsg}"
    ghi list -s open ${sinceparam} | grep -E "^#|NO-ASGN"
}

function buglist-goalline {
    echo "-------- COUNTS OF OPEN ISSUES "
    echo
    buglist-counts

    echo; echo
    echo "-------- OPEN P0's AND P1's BY DEVELOPER"
    echo
    buglist-by-dev

    echo; echo
    echo "-------- ALL OPEN P0 ISSUES"
    echo
    buglist-hot

    echo; echo
    echo "-------- ACTIVE BUGS THAT NEED TRIAGE"
    echo
    buglist-to-triage new

    echo; echo
    echo "-------- ALL ACTIVE ISSUES"
    echo
    buglist-active

    echo; echo
    echo "Notes:"
    echo "- Counts and bug lists exclude bugs marked with \"3-Done\" label."
    echo "- \"Active\" means opened or commented-on in the prior 24 hours."
    echo "- Bugs are sorted with most recent activity on top."
    echo "- \"Needs triage\" means not labeled with P0, P1, P2, or P3."
}


